import java.util.HashMap;
import java.util.Map;

public class TestStr {
    private static final String str = "//desktop/trace/queryDuplicationCustomer,\n" +
            "/desktop/all_company,\n" +
            "/desktop/bluePage,\n" +
            "/desktop/call_manager,\n" +
            "/desktop/callCenter/getCustomerByPhone,\n" +
            "/desktop/callCenter/getGlobalDefaultCallCenterWay,\n" +
            "/desktop/callCenter/getOnLineTimeStamp,\n" +
            "/desktop/callCenter/getPhoneByUserId,\n" +
            "/desktop/callCenter/getPhoneNumByCno,\n" +
            "/desktop/callCenter/getValibAndFreeTableList,\n" +
            "/desktop/callCenter/isThisPhoneBelongsToMyself,\n" +
            "/desktop/callCenter/removeUserTableNo,\n" +
            "/desktop/callCenter/updateDefaultCallCenterWay,\n" +
            "/desktop/callList,\n" +
            "/desktop/clue2ListPage,\n" +
            "/desktop/clueFunnel,\n" +
            "/desktop/clueListPage,\n" +
            "/desktop/communication/queryCallLog,\n" +
            "/desktop/communication/queryCountPhone,\n" +
            "/desktop/connectWorkQA,\n" +
            "/desktop/contact/callCustomerList,\n" +
            "/desktop/contact/dencryptPhone,\n" +
            "/desktop/contact/getLimitedPhoneState,\n" +
            "/desktop/contact/updatePhoneList,\n" +
            "/desktop/contacts_detail,\n" +
            "/desktop/contacts_feedback,\n" +
            "/desktop/contacts_manager,\n" +
            "/desktop/conversation_rule,\n" +
            "/desktop/count_phone,\n" +
            "/desktop/credit_apply_detail,\n" +
            "/desktop/credit_apply_manager,\n" +
            "/desktop/credit_detail,\n" +
            "/desktop/cusConnManage/getCustomerAllRentDetail,\n" +
            "/desktop/cusConnManage/getCustomerCoverRate,\n" +
            "/desktop/cusConnManage/getCustomerCoverRateHistory,\n" +
            "/desktop/cusConnManage/getCustomerDiscardRentDetail,\n" +
            "/desktop/cusConnManage/getCustomerDiscardRentRate,\n" +
            "/desktop/cusConnManage/getCustomerIncreaseRentDetail,\n" +
            "/desktop/cusConnManage/getCustomerIncreaseRentRate,\n" +
            "/desktop/cusConnManage/getCustomerSuccessIncreaseRentDetail,\n" +
            "/desktop/cusConnManage/getCustomerSuccessIncreaseRentRate,\n" +
            "/desktop/cusConnManage/getDepartmentCoverRateHistory,\n" +
            "/desktop/cusConnManage/getDepartmentDiscardRentRate,\n" +
            "/desktop/cusConnManage/getDepartmentIncreaseRentRate,\n" +
            "/desktop/cusConnManage/getOrderdCustomerDetail,\n" +
            "/desktop/cusConnManage/getOrderdCustomerDetailHistory,\n" +
            "/desktop/cusConnManage/goToCustomerAllRentDetail,\n" +
            "/desktop/cusConnManage/goToCustomerDiscardRentDetail,\n" +
            "/desktop/cusConnManage/goToCustomerIncreaseRentDetail,\n" +
            "/desktop/customer_detail,\n" +
            "/desktop/customer_manager,\n" +
            "/desktop/customer_recycled,\n" +
            "/desktop/customer_sale_kit,\n" +
            "/desktop/customer_warning,\n" +
            "/desktop/customer/transfer/assginCustomer,\n" +
            "/desktop/customer/transfer/checkCustomerTransfer,\n" +
            "/desktop/customer/transfer/create,\n" +
            "/desktop/customer/transfer/queryCustomerTransfer,\n" +
            "/desktop/customer/transfer/rejectCustomer,\n" +
            "/desktop/customerConnect/getCoverRate,\n" +
            "/desktop/customerConnect/getDiscardRate,\n" +
            "/desktop/customerConnect/getIncreaseRentRate,\n" +
            "/desktop/customerConnect/getOverdueRate,\n" +
            "/desktop/customerCoverRate,\n" +
            "/desktop/customerCoverRateHistory,\n" +
            "/desktop/customerIndeed/getCustomerIndeedList,\n" +
            "/desktop/customerIndeed/getCustomerIndeedNewDetail,\n" +
            "/desktop/customerIndeed/getCustomerIndeedNewList,\n" +
            "/desktop/customerIndeed/getCustomerIndeedOnlineList,\n" +
            "/desktop/customerIndeed/reInviteNew,\n" +
            "/desktop/customerIndeed/swapIndeed,\n" +
            "/desktop/customerTag,\n" +
            "/desktop/customerTag/getCustomerTagIdList,\n" +
            "/desktop/customerTag/getCustomerTagList,\n" +
            "/desktop/customerTag/getCustomerTagListCount,\n" +
            "/desktop/customerTransfer,\n" +
            "/desktop/cycle/cycleCompleteList,\n" +
            "/desktop/cycleComplementList,\n" +
            "/desktop/department_manager,\n" +
            "/desktop/dest/css/public-16b728df4c.css,\n" +
            "/desktop/dest/css/public-94fcc6c164.css,\n" +
            "/desktop/dest/images/header-dropdown.png,\n" +
            "/desktop/dest/js/public-0abe0ca02e.js,\n" +
            "/desktop/dest/js/public-22f273f6c7.js,\n" +
            "/desktop/dest/js/public-49903f3e3b.js,\n" +
            "/desktop/dest/js/public-6375a5ad32.js,\n" +
            "/desktop/dest/js/public-6c6acf4906.js,\n" +
            "/desktop/dest/js/public-7294ed5a20.js,\n" +
            "/desktop/dest/js/public-8bfdd9c016.js,\n" +
            "/desktop/dest/js/public-a2da31a1ed.js,\n" +
            "/desktop/dest/js/public-aa0d72dbd5.js,\n" +
            "/desktop/dest/js/public-ae83ed5e2c.js,\n" +
            "/desktop/dest/js/public-b0b875de07.js,\n" +
            "/desktop/dest/js/public-d580f3e6a3.js,\n" +
            "/desktop/dispatchCustomer,\n" +
            "/desktop/duplication_manager,\n" +
            "/desktop/elec_customer,\n" +
            "/desktop/elecClue/batchDiscardElecClue,\n" +
            "/desktop/elecClue/batchRestoreElecClue,\n" +
            "/desktop/elecClue/batchTransferElecClue,\n" +
            "/desktop/elecClue/compElecClueList,\n" +
            "/desktop/elecClue/conversionElecClue,\n" +
            "/desktop/elecClue/createElecClue,\n" +
            "/desktop/elecClue/discardElecClue,\n" +
            "/desktop/elecClue/discardElecClueList,\n" +
            "/desktop/elecClue/elecCustomerLog,\n" +
            "/desktop/elecClue/getDataCenter,\n" +
            "/desktop/elecClue/getElecClue,\n" +
            "/desktop/elecClue/onOrOffDataCenter,\n" +
            "/desktop/elecClue/queryCompElecCuleList,\n" +
            "/desktop/elecClue/queryDiscardElecCuleList,\n" +
            "/desktop/elecClue/queryElecCuleCount,\n" +
            "/desktop/elecClue/queryWaitElecCuleList,\n" +
            "/desktop/elecClue/restoreElecClue,\n" +
            "/desktop/elecClue/selectDataCenter,\n" +
            "/desktop/elecClue/updateElecClue,\n" +
            "/desktop/elecClue/waitElecCuleList,\n" +
            "/desktop/enter_error_order,\n" +
            "/desktop/enterReturnOrderKPIDetail2,\n" +
            "/desktop/enterReturnOrderKPIDetail3,\n" +
            "/desktop/feedbackPool,\n" +
            "/desktop/getCustomerDiscardRentRate,\n" +
            "/desktop/getCustomerIncreaseRentRate,\n" +
            "/desktop/getCustomerSuccessIncreaseRentRate,\n" +
            "/desktop/getOrderdCustomerDetail,\n" +
            "/desktop/getOrderdCustomerDetailHistory,\n" +
            "/desktop/getOverdueStatListNewView,\n" +
            "/desktop/getScheduledTaskSetList,\n" +
            "/desktop/goToCustomerSuccessAllRentDetail,\n" +
            "/desktop/goToCustomerSuccessIncreaseRentDetail,\n" +
            "/desktop/goToDepartmentConnCoverRate,\n" +
            "/desktop/goToDepartmentDiscardRentRate,\n" +
            "/desktop/goToDepartmentDueOverDateRate,\n" +
            "/desktop/goToDepartmentIncreaseRentRate,\n" +
            "/desktop/goToDepartmentMoneyOverdateRateRate,\n" +
            "/desktop/goToNewDepartmentMoneyOverdateRateRate,\n" +
            "/desktop/goToRemarkPage,\n" +
            "/desktop/groupCompany,\n" +
            "/desktop/highsea_detail,\n" +
            "/desktop/highsea_manager,\n" +
            "/desktop/highsea_rule,\n" +
            "/desktop/highseaExcavateNewPage,\n" +
            "/desktop/highseaExcavatePage,\n" +
            "/desktop/home_page,\n" +
            "/desktop/home_page_manage,\n" +
            "/desktop/home/addOrEditRank,\n" +
            "/desktop/home/queryHome,\n" +
            "/desktop/improve_apply_detail,\n" +
            "/desktop/indeedNewPage,\n" +
            "/desktop/indeedPage,\n" +
            "/desktop/index,\n" +
            "/desktop/invoice,\n" +
            "/desktop/kaProject/createKaProjectTask,\n" +
            "/desktop/kaProject/getKaNewProjectList,\n" +
            "/desktop/kaProject/getKaProjectInfo,\n" +
            "/desktop/kaProject/getKaProjectStageInfoList,\n" +
            "/desktop/kaProject/getKaProjectUndoneTaskList,\n" +
            "/desktop/kaProject/getKaRenewProjectList,\n" +
            "/desktop/kaProject/kaProjectManage,\n" +
            "/desktop/kaProject/myCalendar,\n" +
            "/desktop/kaProject/myCalendarData,\n" +
            "/desktop/kaProject/pagination/getKaNewProjectList,\n" +
            "/desktop/kaProject/pagination/getKaProjectCompleteTaskList,\n" +
            "/desktop/kaProject/pagination/getKaRenewProjectList,\n" +
            "/desktop/kaProject/toKaNewProjectList,\n" +
            "/desktop/kaProject/toKaProjectStageList,\n" +
            "/desktop/kaProject/toKaRenewProjectList,\n" +
            "/desktop/logout,\n" +
            "/desktop/mailTools/batchSendMails,\n" +
            "/desktop/mailTools/batchSendMailsV3,\n" +
            "/desktop/mailTools/checkAvailability,\n" +
            "/desktop/mailTools/checkMailIsAvailable,\n" +
            "/desktop/mailTools/delMailTemplate,\n" +
            "/desktop/mailTools/exportSendMailCountList,\n" +
            "/desktop/mailTools/findTemplates,\n" +
            "/desktop/mailTools/getMailSendCountList,\n" +
            "/desktop/mailTools/getMailTemplate,\n" +
            "/desktop/mailTools/jumpToMailSendCountPage,\n" +
            "/desktop/mailTools/mailCertification,\n" +
            "/desktop/mailTools/mailLogout,\n" +
            "/desktop/mailTools/mailSendPageV3,\n" +
            "/desktop/mailTools/mailTemplate,\n" +
            "/desktop/mailTools/mailTemplateV3,\n" +
            "/desktop/mailTools/mailToolsV2,\n" +
            "/desktop/mailTools/mailToolsV3,\n" +
            "/desktop/mailTools/saveCopyLog,\n" +
            "/desktop/mailTools/saveMailTemplate,\n" +
            "/desktop/mailTools/searchMailInfo2,\n" +
            "/desktop/mailTools/searchMailInfoV3,\n" +
            "/desktop/mailTools/updateMailTemplate,\n" +
            "/desktop/mailTools/uploadMailFile,\n" +
            "/desktop/mailTools/validateUserMail,\n" +
            "/desktop/message_manager,\n" +
            "/desktop/message/batchMessageReaded,\n" +
            "/desktop/message/getCustomerImprove,\n" +
            "/desktop/message/getSalePushMsg,\n" +
            "/desktop/message/getSaleRecordMessage,\n" +
            "/desktop/message/getSpecificCustomer,\n" +
            "/desktop/message/isMySelfCustomer,\n" +
            "/desktop/message/markMessageReaded,\n" +
            "/desktop/message/updateSalePushMsg,\n" +
            "/desktop/modifyPwd,\n" +
            "/desktop/my_company,\n" +
            "/desktop/myCustomerWithOrder,\n" +
            "/desktop/myPrivateSeaOne,\n" +
            "/desktop/myPrivateSeaThree,\n" +
            "/desktop/order_detail,\n" +
            "/desktop/order_manager,\n" +
            "/desktop/organization/createDepartment,\n" +
            "/desktop/organization/modifyDepartment,\n" +
            "/desktop/organization/queryDepartment,\n" +
            "/desktop/organization/querydockedDepartmentByDepartmentId,\n" +
            "/desktop/organization/queryIndustryFirst,\n" +
            "/desktop/organization/queryStructure,\n" +
            "/desktop/oss/getSign,\n" +
            "/desktop/overdueCase,\n" +
            "/desktop/overdueStat/getDepartmentOverdueStatNewList,\n" +
            "/desktop/overdueStat/getOverdueStatDetailList,\n" +
            "/desktop/overdueStat/getOverdueStatDetailView,\n" +
            "/desktop/overdueStat/getOverdueStatList,\n" +
            "/desktop/overdueStat/getOverdueStatListDepartment,\n" +
            "/desktop/overdueStat/getOverdueStatListView,\n" +
            "/desktop/overdueStat/getOverdueStatNewDetails,\n" +
            "/desktop/overdueStat/getOverdueStatNewDetailsManager,\n" +
            "/desktop/overdueStat/getOverdueStatNewList,\n" +
            "/desktop/overdueStat/getOverdueStatNewListManager,\n" +
            "/desktop/overdueStat/getoverdueStatNewMonthDetails,\n" +
            "/desktop/overdueStat/getoverdueStatNewMonthDetailsManager,\n" +
            "/desktop/overdueStat/getOverdueStatNewOrderDetailMonthView,\n" +
            "/desktop/overdueStat/getOverdueStatNewOrderDetailView,\n" +
            "/desktop/overdueStat/getOverdueStatOrderDetailList,\n" +
            "/desktop/overdueStat/getOverdueStatOrderDetailView,\n" +
            "/desktop/peopleWorkManagement/getPeopleWorkManagementDepartmentList,\n" +
            "/desktop/peopleWorkManagement/getPeopleWorkManagementList,\n" +
            "/desktop/peopleWorkManagement/gotoPeopleWorkManagementView,\n" +
            "/desktop/permission/createMenu,\n" +
            "/desktop/permission/createRight,\n" +
            "/desktop/permission/createRole,\n" +
            "/desktop/permission/createUser,\n" +
            "/desktop/permission/getMenu,\n" +
            "/desktop/permission/getVisibleRoleList,\n" +
            "/desktop/permission/modifyMyPassword,\n" +
            "/desktop/permission/modifyRole,\n" +
            "/desktop/permission/modifyRoleRight,\n" +
            "/desktop/permission/modifyUser,\n" +
            "/desktop/permission/modifyWorkPhone,\n" +
            "/desktop/permission/queryMenuRight,\n" +
            "/desktop/permission/queryMyMenu,\n" +
            "/desktop/permission/queryRole,\n" +
            "/desktop/permission/queryRoleRight,\n" +
            "/desktop/permission/queryUser,\n" +
            "/desktop/permission/queryUserInfoById,\n" +
            "/desktop/permission/queryUserPrivateSeaInfoByUserId,\n" +
            "/desktop/permission/resetPassword,\n" +
            "/desktop/permission/updatePrivateSeaColumns,\n" +
            "/desktop/permission/updateUserPrivateSeaInfoByUserId,\n" +
            "/desktop/privateCustomerTwo/countPrivateCustomerTwoCategory,\n" +
            "/desktop/privateCustomerTwo/getPrivateCustomerTwoList,\n" +
            "/desktop/privateCustomerTwo/toList,\n" +
            "/desktop/privateCustomerTwo/updatePrivateCustomerTwoCategory,\n" +
            "/desktop/quotedPrice/addPlan,\n" +
            "/desktop/quotedPrice/getOtherCondition,\n" +
            "/desktop/quotedPrice/queryQuotedPriceList,\n" +
            "/desktop/quotedPrice/quotedPriceList,\n" +
            "/desktop/quotedPrice/quotePriceDetail,\n" +
            "/desktop/redirect,\n" +
            "/desktop/remainStaff/getRemainStaffDepartmentList,\n" +
            "/desktop/remainStaff/getRemainStaffDetail,\n" +
            "/desktop/remainStaff/getRemainStaffList,\n" +
            "/desktop/remainStaff/gotoRemainStaffView,\n" +
            "/desktop/remark/addComment,\n" +
            "/desktop/remark/getCustomerRemarkList,\n" +
            "/desktop/remark/getOneComment,\n" +
            "/desktop/renew_detail,\n" +
            "/desktop/renew_manager,\n" +
            "/desktop/repay2Detail,\n" +
            "/desktop/report/addDeadAccount,\n" +
            "/desktop/report/customerConstitute,\n" +
            "/desktop/report/deadAccountList,\n" +
            "/desktop/report/dealDeadAccount,\n" +
            "/desktop/report/delDeadAccount,\n" +
            "/desktop/report/exportDeadAccount,\n" +
            "/desktop/report/exportOverdue30BillStat,\n" +
            "/desktop/report/getClueFunnelCount,\n" +
            "/desktop/report/getCustomerConstituteDetail,\n" +
            "/desktop/report/getRentDetail,\n" +
            "/desktop/report/getRentStat,\n" +
            "/desktop/report/getReturnOrderAnalysis,\n" +
            "/desktop/report/getReturnOrderKPI,\n" +
            "/desktop/report/getReturnOrderKPI2,\n" +
            "/desktop/report/getReturnOrderKPI3,\n" +
            "/desktop/report/getSaleFunnelDepartmentPage,\n" +
            "/desktop/report/getSaleFunnelDetailPage,\n" +
            "/desktop/report/getSaleFunnelPersonPage,\n" +
            "/desktop/report/getSalePerformanceStat,\n" +
            "/desktop/report/kpiStat3,\n" +
            "/desktop/report/kpiStat4,\n" +
            "/desktop/report/kpiStatV3,\n" +
            "/desktop/report/overdue30BillDetail,\n" +
            "/desktop/report/pay2CustomerDetail,\n" +
            "/desktop/report/pay2Detail,\n" +
            "/desktop/report/queryCustomerAndContactsStat,\n" +
            "/desktop/report/queryFinishStat,\n" +
            "/desktop/report/queryOrderStat,\n" +
            "/desktop/report/querySaleDptKPI,\n" +
            "/desktop/report/querySaleGoal,\n" +
            "/desktop/report/querySalePerformanceOtherNum,\n" +
            "/desktop/report/querySalePerformanceReport,\n" +
            "/desktop/report/querySaleRecordStat,\n" +
            "/desktop/report/repay2Detail,\n" +
            "/desktop/report/repay2Page,\n" +
            "/desktop/report/repayView,\n" +
            "/desktop/report/reportSaleFunnelPerson,\n" +
            "/desktop/report/save,\n" +
            "/desktop/report/searchCustomer,\n" +
            "/desktop/report/searchCustomerConstituteResult,\n" +
            "/desktop/report/searchEachDayOnRentStatistics,\n" +
            "/desktop/report/show4StatDetail,\n" +
            "/desktop/report/showCustomerConstituteDetail,\n" +
            "/desktop/report/showRentStatDetail,\n" +
            "/desktop/report/showRentView,\n" +
            "/desktop/report/showReturnOrderKPIDetail2,\n" +
            "/desktop/report/showReturnOrderKPIDetail3,\n" +
            "/desktop/report/showStatCustomer4Detail,\n" +
            "/desktop/report/showStatCustomerDetail,\n" +
            "/desktop/report/showStatDetail,\n" +
            "/desktop/report/statOverdue30Bill,\n" +
            "/desktop/report/statPay2,\n" +
            "/desktop/report/statRepay2,\n" +
            "/desktop/report/statRepayList,\n" +
            "/desktop/return_order,\n" +
            "/desktop/return_order_analysis,\n" +
            "/desktop/return_order_detail,\n" +
            "/desktop/return_order_kpi,\n" +
            "/desktop/return_order_kpi2,\n" +
            "/desktop/return_order_kpi3,\n" +
            "/desktop/returnHighSeaSet/getReturnHighSeaSetListData,\n" +
            "/desktop/role_manager,\n" +
            "/desktop/sale_analysis,\n" +
            "/desktop/sale_behavior_analysis,\n" +
            "/desktop/sale_dpt_kpi_v2,\n" +
            "/desktop/sale_dpt_kpi_v3,\n" +
            "/desktop/sale_goal,\n" +
            "/desktop/sale_performance,\n" +
            "/desktop/sale_performance_3,\n" +
            "/desktop/sale_performance_4,\n" +
            "/desktop/sale_performance_v3,\n" +
            "/desktop/sale_record,\n" +
            "/desktop/sale_record_detail,\n" +
            "/desktop/sale_record_manager,\n" +
            "/desktop/saleCollect,\n" +
            "/desktop/saleFunnel,\n" +
            "/desktop/saleFunnelDetail,\n" +
            "/desktop/saleHelper,\n" +
            "/desktop/saleHelperDetail,\n" +
            "/desktop/saleHelperManage,\n" +
            "/desktop/saleHelperModify,\n" +
            "/desktop/saleHelperTag,\n" +
            "/desktop/saleRecordImage,\n" +
            "/desktop/sales_performance_forecast,\n" +
            "/desktop/saleScore/list,\n" +
            "/desktop/saleScore/listView,\n" +
            "/desktop/salesPerformanceForecast/query,\n" +
            "/desktop/salesPerformanceForecast/save,\n" +
            "/desktop/saletool/stockquery/queryStock,\n" +
            "/desktop/saletool/stockquery/queryStockList,\n" +
            "/desktop/scheduledTaskSet/getScheduledTaskSetData,\n" +
            "/desktop/scheduledTaskSet/gotoReturnHighSea,\n" +
            "/desktop/scheduledTaskSet/updateTaskStatus,\n" +
            "/desktop/show4StatDetail,\n" +
            "/desktop/showOtherDetail,\n" +
            "/desktop/showRemainStaffDetail,\n" +
            "/desktop/showStat4CustomerDetail,\n" +
            "/desktop/showStatCustomerDetail,\n" +
            "/desktop/showStatDetail,\n" +
            "/desktop/sJudgementPage,\n" +
            "/desktop/smart/bluePage/transform,\n" +
            "/desktop/smart/cleanUserClues,\n" +
            "/desktop/smart/clue2List,\n" +
            "/desktop/smart/clueRecommend,\n" +
            "/desktop/smart/desertClue,\n" +
            "/desktop/smart/privateClueList,\n" +
            "/desktop/smart/privateCluePage,\n" +
            "/desktop/smart/privateClueStatistic,\n" +
            "/desktop/smart/queryBluePageList,\n" +
            "/desktop/smart/queryPrivateClueCount,\n" +
            "/desktop/smart/recommendData,\n" +
            "/desktop/smart/searchCompanyInfoFromSpider,\n" +
            "/desktop/smart/statPrivateClues,\n" +
            "/desktop/smart/transferUserClues,\n" +
            "/desktop/smart/transformClue2,\n" +
            "/desktop/smart/updatePrivateClueStatus,\n" +
            "/desktop/sop/deleteSopPersonTask,\n" +
            "/desktop/sop/editSopConfig,\n" +
            "/desktop/sop/editSopPersonTask,\n" +
            "/desktop/sop/editSopTaskStatus,\n" +
            "/desktop/sop/exportSopTaskList,\n" +
            "/desktop/sop/getFinishSopTaskIndex,\n" +
            "/desktop/sop/getSopConfig,\n" +
            "/desktop/sop/getSopConfigListPage,\n" +
            "/desktop/sop/getSopRole,\n" +
            "/desktop/sop/getSopTaskCountList,\n" +
            "/desktop/sop/getSopTaskPage,\n" +
            "/desktop/sop/getWaitSopTaskIndex,\n" +
            "/desktop/sop/gotoSopTask,\n" +
            "/desktop/sop/removeSopConfig,\n" +
            "/desktop/stockQueryPage,\n" +
            "/desktop/trace/addLogForSelectBill,\n" +
            "/desktop/trace/addSaleCollect,\n" +
            "/desktop/trace/assignUnmatchedOrder,\n" +
            "/desktop/trace/automaticFillingAddress,\n" +
            "/desktop/trace/batchJudge,\n" +
            "/desktop/trace/batchUnbindFollower,\n" +
            "/desktop/trace/batchUpdateCusFollower,\n" +
            "/desktop/trace/bindOtherPrivateSeaOne,\n" +
            "/desktop/trace/checkAttachmentExist,\n" +
            "/desktop/trace/checkCustomerOwn,\n" +
            "/desktop/trace/checkDuplicateCustomer,\n" +
            "/desktop/trace/checkPhoneIsExitById,\n" +
            "/desktop/trace/checkPhoneUseNum,\n" +
            "/desktop/trace/clue/transformCustomerWithClueId,\n" +
            "/desktop/trace/createContacts,\n" +
            "/desktop/trace/createContactsFeedback,\n" +
            "/desktop/trace/createSaleRecordReply,\n" +
            "/desktop/trace/credit/improve/apply,\n" +
            "/desktop/trace/credit/improveApply/close,\n" +
            "/desktop/trace/credit/list/customer,\n" +
            "/desktop/trace/credit/overdue/detail,\n" +
            "/desktop/trace/credit/overdue/list,\n" +
            "/desktop/trace/credit/overdue/saleCommentCase,\n" +
            "/desktop/trace/delete_white_list,\n" +
            "/desktop/trace/deleteSaleRecordReply,\n" +
            "/desktop/trace/exportCustomerAbstract,\n" +
            "/desktop/trace/exportCustomerOrder,\n" +
            "/desktop/trace/feedbackPoolDetail,\n" +
            "/desktop/trace/feedbackPoolList,\n" +
            "/desktop/trace/findGroupCompanyList,\n" +
            "/desktop/trace/findSaleRecordModifyLog,\n" +
            "/desktop/trace/getContactsDetail,\n" +
            "/desktop/trace/getCustomerAddress,\n" +
            "/desktop/trace/getCustomerDetail,\n" +
            "/desktop/trace/getCustomerDispatchPage,\n" +
            "/desktop/trace/getCustomerList,\n" +
            "/desktop/trace/getDateTime,\n" +
            "/desktop/trace/getDeviceList,\n" +
            "/desktop/trace/getDiscountRuleList,\n" +
            "/desktop/trace/getElecConversionLog,\n" +
            "/desktop/trace/getHighSeaCount,\n" +
            "/desktop/trace/getOrderCustomerList,\n" +
            "/desktop/trace/getSaleCollectCount,\n" +
            "/desktop/trace/getSaleHelperTag,\n" +
            "/desktop/trace/getSaleRecordDoorPerson,\n" +
            "/desktop/trace/getUserEnablePrivateSeaList,\n" +
            "/desktop/trace/getUserFristPrivateSea,\n" +
            "/desktop/trace/groupDetails,\n" +
            "/desktop/trace/highsea/batchBindFollower,\n" +
            "/desktop/trace/highsea/queryHighsea4ExcavateNew,\n" +
            "/desktop/trace/isSaleCollect,\n" +
            "/desktop/trace/judgeLogPage,\n" +
            "/desktop/trace/modifyContacts,\n" +
            "/desktop/trace/modifyCustomer,\n" +
            "/desktop/trace/modifyJudgeResult,\n" +
            "/desktop/trace/modifyOrder,\n" +
            "/desktop/trace/modifyReturnOrder,\n" +
            "/desktop/trace/modifySaleCollect,\n" +
            "/desktop/trace/modifySaleRecord,\n" +
            "/desktop/trace/query_conversation_rule,\n" +
            "/desktop/trace/query_error_order,\n" +
            "/desktop/trace/query_white_list,\n" +
            "/desktop/trace/queryClueList,\n" +
            "/desktop/trace/queryContactsAbstract,\n" +
            "/desktop/trace/queryContactsFeedback,\n" +
            "/desktop/trace/queryContactsLog,\n" +
            "/desktop/trace/queryCustomerAbstract,\n" +
            "/desktop/trace/queryCustomerAbstract1,\n" +
            "/desktop/trace/queryCustomerCallLog,\n" +
            "/desktop/trace/queryCustomerOrder,\n" +
            "/desktop/trace/queryDuplicationCustomer,\n" +
            "/desktop/trace/queryelecCustomer,\n" +
            "/desktop/trace/queryGhostLink,\n" +
            "/desktop/trace/queryHighseaAbstract,\n" +
            "/desktop/trace/queryInvoiceList,\n" +
            "/desktop/trace/queryMyCustomerAmount,\n" +
            "/desktop/trace/queryMyImproveApplyCustomerList,\n" +
            "/desktop/trace/queryOrderExpiresStatus,\n" +
            "/desktop/trace/queryRecycledCustomer,\n" +
            "/desktop/trace/queryRenewOrderFromCRM,\n" +
            "/desktop/trace/queryRenewOrderNoById,\n" +
            "/desktop/trace/queryReturnOrder,\n" +
            "/desktop/trace/querySaleLog,\n" +
            "/desktop/trace/querySaleRecord,\n" +
            "/desktop/trace/querySaleRecordReply,\n" +
            "/desktop/trace/querySJudgeLog,\n" +
            "/desktop/trace/querySJudgementList,\n" +
            "/desktop/trace/queryUnmatchedOrder,\n" +
            "/desktop/trace/queryWarningCustomer,\n" +
            "/desktop/trace/recycleCustomer,\n" +
            "/desktop/trace/removeAllUserSjudgement,\n" +
            "/desktop/trace/removeSaleCollect,\n" +
            "/desktop/trace/removeSaleHelperAttachment,\n" +
            "/desktop/trace/reportFeedbackPool,\n" +
            "/desktop/trace/saleCollectList,\n" +
            "/desktop/trace/saleHelperList,\n" +
            "/desktop/trace/saleHelperManageList,\n" +
            "/desktop/trace/saleHelperTagCount,\n" +
            "/desktop/trace/saveFeedbackPool,\n" +
            "/desktop/trace/saveSaleHelper,\n" +
            "/desktop/trace/saveWhiteList,\n" +
            "/desktop/trace/showAllReturn,\n" +
            "/desktop/trace/sJudge,\n" +
            "/desktop/trace/synchronizationJudge,\n" +
            "/desktop/trace/unbindFollower,\n" +
            "/desktop/trace/updateBizChance,\n" +
            "/desktop/trace/updateContactsFeedback,\n" +
            "/desktop/trace/updateFeedbackPool,\n" +
            "/desktop/trace/updateOverdueCustomer,\n" +
            "/desktop/trace/upgradePrivateSea,\n" +
            "/desktop/trace/uploadAttachment,\n" +
            "/desktop/trace/uploadSaleHelperImage,\n" +
            "/desktop/trace/userSearch,\n" +
            "/desktop/uniteFollow/queryList,\n" +
            "/desktop/uniteFollow/viewPage,\n" +
            "/desktop/unmatched_order,\n" +
            "/desktop/user_manager,\n" +
            "/desktop/white_list,\n" +
            "/desktop/workFunnel,\n" +
            "/mobile/communication/queryCallLog,\n" +
            "/mobile/communication/queryWhiteNumberProfile,\n" +
            "/mobile/communication/searchPhoneRecord,\n" +
            "/mobile/credit/getCustomerIndeedDetail,\n" +
            "/mobile/credit/getCustomerIndeedList,\n" +
            "/mobile/credit/getExtraCreditList,\n" +
            "/mobile/credit/getImproverPlanList,\n" +
            "/mobile/credit/quotedPrice/queryQuotedPriceList,\n" +
            "/mobile/credit/quotedPrice/quotePriceConditions,\n" +
            "/mobile/credit/quotedPrice/quotePriceDetail,\n" +
            "/mobile/credit/reInvite,\n" +
            "/mobile/credit/stockquery/queryStock,\n" +
            "/mobile/credit/stockquery/queryStockList,\n" +
            "/mobile/message/markMessageReaded,\n" +
            "/mobile/message/queryMessageProfile,\n" +
            "/mobile/organization/queryCity,\n" +
            "/mobile/organization/queryProvince,\n" +
            "/mobile/organization/queryStructure,\n" +
            "/mobile/permission/getMyUser,\n" +
            "/mobile/permission/modifyMyPassword,\n" +
            "/mobile/permission/reportLaunch,\n" +
            "/mobile/permission/updateMobileDevice,\n" +
            "/mobile/report/queryPerformanceStatMobile,\n" +
            "/mobile/sign/querySignRecordProfile,\n" +
            "/mobile/sign/reportSignRecord,\n" +
            "/mobile/synergy/getSynergyOrderDetail,\n" +
            "/mobile/synergy/querySynergyOrderReplyProfile,\n" +
            "/mobile/trace/addSaleCollect,\n" +
            "/mobile/trace/addUrgeReceiables,\n" +
            "/mobile/trace/bindFollower,\n" +
            "/mobile/trace/bindOtherPrivateSeaOne,\n" +
            "/mobile/trace/connectWorkQA,\n" +
            "/mobile/trace/createContacts,\n" +
            "/mobile/trace/createCustomer,\n" +
            "/mobile/trace/createSaleRecord,\n" +
            "/mobile/trace/customerDetailTagNum,\n" +
            "/mobile/trace/getContactsDetail,\n" +
            "/mobile/trace/getContactsOption,\n" +
            "/mobile/trace/getCreditApplyDetail,\n" +
            "/mobile/trace/getCustomerDetail,\n" +
            "/mobile/trace/getCustomerOption,\n" +
            "/mobile/trace/getHighseaDetail,\n" +
            "/mobile/trace/getImproveApplyDetail,\n" +
            "/mobile/trace/getOrderDetail,\n" +
            "/mobile/trace/getOrderOption,\n" +
            "/mobile/trace/getReturnOrderDetail,\n" +
            "/mobile/trace/improve/apply,\n" +
            "/mobile/trace/modifyCustomer,\n" +
            "/mobile/trace/queryContactsProfile,\n" +
            "/mobile/trace/queryCreditApplyProfile,\n" +
            "/mobile/trace/queryCusomerByName,\n" +
            "/mobile/trace/queryCustomerBrief,\n" +
            "/mobile/trace/queryCustomerProfile,\n" +
            "/mobile/trace/queryDuplicationCustomer,\n" +
            "/mobile/trace/queryHighseaProfile,\n" +
            "/mobile/trace/queryImproveApplyProfile,\n" +
            "/mobile/trace/queryNearbyCustomer,\n" +
            "/mobile/trace/queryNearbyCustomerList,\n" +
            "/mobile/trace/queryNearbyCustomerMap,\n" +
            "/mobile/trace/queryOrderProfile,\n" +
            "/mobile/trace/queryReturnOrderProfile,\n" +
            "/mobile/trace/querySaleLog,\n" +
            "/mobile/trace/querySaleRecordProfile,\n" +
            "/mobile/trace/querySJudgeLog,\n" +
            "/mobile/trace/querySJudgementList,\n" +
            "/mobile/trace/queryUrgeSaleRecordProfile,\n" +
            "/mobile/trace/sJudge,\n" +
            "/mobile/trace/unbindFollower,\n" +
            "/mobile/trace/upgradePrivateSea,";

    private static final String menu = "消息,\n" +
            "首页,\n" +
            "线索,\n" +
            "我的线索,\n" +
            "客户,\n" +
            "未匹配客户,\n" +
            "客户公海,\n" +
            "客户查重,\n" +
            "联系人,\n" +
            "电商线索,\n" +
            "私海1,\n" +
            "私海2,\n" +
            "私海3,\n" +
            "成单客户,\n" +
            "客户回收站,\n" +
            "客户转接,\n" +
            "集团账户,\n" +
            "客户收藏,\n" +
            "待转化线索,\n" +
            "已转化线索,\n" +
            "已废弃线索,\n" +
            "分发的客户,\n" +
            "销售记录,\n" +
            "邮件发送,\n" +
            "打电话列表,\n" +
            "线索库,\n" +
            "客户等级判定,\n" +
            "公海挖掘,\n" +
            "邮箱工具,\n" +
            "库存查询,\n" +
            "企业名录,\n" +
            "线索库2.0,\n" +
            "订单管理,\n" +
            "未匹配订单,\n" +
            "退租管理,\n" +
            "续租订单,\n" +
            "授信申请,\n" +
            "提额申请,\n" +
            "提额方案,\n" +
            "押金金融,\n" +
            "补充授信记录,\n" +
            "实地签约,\n" +
            "逾期案件,\n" +
            "目标与达成,\n" +
            "绩效业绩表,\n" +
            "销售分析,\n" +
            "工作记录表,\n" +
            "退租报表分析,\n" +
            "销售过程统计,\n" +
            "绩效业绩表2,\n" +
            "销售部统计表,\n" +
            "在租统计,\n" +
            "绩效业绩表3,\n" +
            "退租绩效报表,\n" +
            "销售部统计表2,\n" +
            "回款统计,\n" +
            "销售漏斗,\n" +
            "通话记录,\n" +
            "通话统计,\n" +
            "部门管理,\n" +
            "角色管理,\n" +
            "用户管理,\n" +
            "反馈池,\n" +
            "防骚扰白名单,\n" +
            "通话规则设置,\n" +
            "错误订单,\n" +
            "智能公海,\n" +
            "发票管理,\n" +
            "公海挖掘3.0,\n" +
            "报价库,\n" +
            "联合跟进,\n" +
            "线索漏斗,\n" +
            "工作统计,\n" +
            "线索推荐,\n" +
            "个人线索库,\n" +
            "我的日历,\n" +
            "项目过程管理,\n" +
            "成单项目管理,\n" +
            "回款统计2.0,\n" +
            "回归公海设置,\n" +
            "人效管理统计,\n" +
            "人员留存统计,\n" +
            "邮箱工具3,\n" +
            "分发记录,\n" +
            "客户数据处理池,\n" +
            "客户构成统计,\n" +
            "销售部统计表3,\n" +
            "绩效业绩表4,\n" +
            "退租绩效报表2,\n" +
            "客户-运营导出,\n" +
            "实地签约(new),\n" +
            "定期补充资料,\n" +
            "客户成功上门覆盖率,\n" +
            "客户逾期率,\n" +
            "销售业绩预测,\n" +
            "全退租率,\n" +
            "增租率,\n" +
            "客户上门覆盖率,\n" +
            "标签管理,\n" +
            "客户上门覆盖率(部门)(old),\n" +
            "全退租(部门)(old),\n" +
            "增租率(部门)(old),\n" +
            "逾期率统计(部门)(old),\n" +
            "账单逾期率(old),\n" +
            "客户成功增租率(old),\n" +
            "账单逾期率(部门)(old),\n" +
            "增租率,\n" +
            "上门覆盖率,\n" +
            "客户逾期率,\n" +
            "全退租,\n" +
            "账单逾期率,\n" +
            "退租绩效报表3,\n" +
            "外访记录,\n" +
            "提问,\n" +
            "sop任务,\n" +
            "开票管理,";
    private static final String href = "message_manager,\n" +
            "home_page,\n" +
            "all_company,\n" +
            "my_company,\n" +
            "customer_manager,\n" +
            "unmatched_customer,\n" +
            "highsea_manager,\n" +
            "duplication_manager,\n" +
            "contacts_manager,\n" +
            "elec_customer,\n" +
            "myPrivateSeaOne,\n" +
            "privateCustomerTwo/toList,\n" +
            "myPrivateSeaThree,\n" +
            "myCustomerWithOrder,\n" +
            "customer_warning,\n" +
            "customerTransfer,\n" +
            "groupCompany,\n" +
            "saleCollect,\n" +
            "elecClue/waitElecCuleList,\n" +
            "elecClue/compElecClueList,\n" +
            "elecClue/discardElecClueList,\n" +
            "dispatchCustomer,\n" +
            "sale_record_manager,\n" +
            "mail/mailSendForwardPage,\n" +
            "callListForwardPage,\n" +
            "clueListPage,\n" +
            "sJudgementPage,\n" +
            "highseaExcavatePage,\n" +
            "mailTools/mailToolsV2,\n" +
            "stockQueryPage,\n" +
            "bluePage,\n" +
            "clue2ListPage,\n" +
            "order_manager,\n" +
            "unmatched_order,\n" +
            "return_order,\n" +
            "renew_manager,\n" +
            "credit_apply_manager?type=1,\n" +
            "credit_apply_manager?type=2,\n" +
            "credit_apply_manager?type=3,\n" +
            "credit_apply_manager?type=4,\n" +
            "credit_apply_manager?type=5,\n" +
            "indeedPage,\n" +
            "overdueCase,\n" +
            "sale_goal,\n" +
            "sale_performance,\n" +
            "sale_analysis,\n" +
            "sale_record,\n" +
            "return_order_analysis,\n" +
            "sale_behavior_analysis,\n" +
            "sale_performance_v3,\n" +
            "saleDepartmentStat,\n" +
            "report/showRentView,\n" +
            "sale_performance_3,\n" +
            "return_order_kpi,\n" +
            "sale_dpt_kpi_v2,\n" +
            "report/repayView,\n" +
            "saleFunnel,\n" +
            "call_manager,\n" +
            "count_phone,\n" +
            "department_manager,\n" +
            "role_manager,\n" +
            "user_manager,\n" +
            "feedlbackPool,\n" +
            "white_list,\n" +
            "conversation_rule,\n" +
            "enter_error_order,\n" +
            "smartHighSeaPage,\n" +
            "invoice,\n" +
            "highseaExcavateNewPage,\n" +
            "quotedPrice/quotedPriceList,\n" +
            "uniteFollow/viewPage,\n" +
            "clueFunnel,\n" +
            "workFunnel,\n" +
            "smart/clueRecommend,\n" +
            "smart/privateCluePage,\n" +
            "kaProject/myCalendar,\n" +
            "kaProject/toKaNewProjectList,\n" +
            "kaProject/toKaRenewProjectList,\n" +
            "report/repay2Page,\n" +
            "getScheduledTaskSetList,\n" +
            "peopleWorkManagement/gotoPeopleWorkManagementView,\n" +
            "remainStaff/gotoRemainStaffView,\n" +
            "mailTools/mailToolsV3,\n" +
            "elecClue/elecCustomerLog,\n" +
            "contacts_feedback,\n" +
            "report/customerConstitute,\n" +
            "sale_dpt_kpi_v3,\n" +
            "sale_performance_4,\n" +
            "return_order_kpi2,\n" +
            "trace/operate_exportCustomer,\n" +
            "indeedNewPage,\n" +
            "cycleComplementList,\n" +
            "customerCoverRate,\n" +
            "overdueStat/getOverdueStatListView,\n" +
            "sales_performance_forecast,\n" +
            "getCustomerDiscardRentRate,\n" +
            "getCustomerIncreaseRentRate,\n" +
            "customerCoverRateHistory,\n" +
            "customerTag,\n" +
            "goToDepartmentConnCoverRate,\n" +
            "goToDepartmentDiscardRentRate,\n" +
            "goToDepartmentIncreaseRentRate,\n" +
            "goToDepartmentDueOverDateRate,\n" +
            "getOverdueStatListNewView,\n" +
            "getCustomerSuccessIncreaseRentRate,\n" +
            "goToDepartmentMoneyOverdateRateRate,\n" +
            "customerConnect/getIncreaseRentRate,\n" +
            "customerConnect/getCoverRate,\n" +
            "customerConnect/getOverdueRate,\n" +
            "customerConnect/getDiscardRate,\n" +
            "goToNewDepartmentMoneyOverdateRateRate,\n" +
            "return_order_kpi3,\n" +
            "saleRecord/gotoUrgeList,\n" +
            "feedbackPool,\n" +
            "sop/gotoSopTask,\n" +
            "invoice/gotoInvoiceManager,";
    private static final Map<String, String> map = new HashMap<>();
    private static final Map<String, String> map1 = new HashMap<>();

    public static void main(String[] args) {
        String[] arr = str.split(",");
        String[] arr1 = menu.split(",");
        String[] arr2 = href.split(",");
        for (int i = 0; i < arr1.length; i++) {
            map.put(arr2[i], arr1[i]);
        }
    }
}
